
#
# Mount point(s)
# <host path>:<Docker path>
#
# Predefined environment variable(s):
#   HOME
#   DOCKER_USER
#   OS_NAME
#
%HOST_DIR%:/home/${DOCKER_USER}/${OS_NAME}
#${HOME}/.ssh:/home/${DOCKER_USER}/.ssh
