#
# Dockerized Yocto Build
#

# Use Ubuntu 24.04 LTS as the basis for the Docker image
ARG BASE_IMAGE=ubuntu:24.04
FROM ${BASE_IMAGE}

LABEL maintainer="adrian.bularca@gmail.com"
# LABEL version="0.1"
LABEL description="Custom Docker image for building Nvidia Jetson Linux platform"

ARG DEBIAN_FRONTEND=noninteractive

ENV USER_NAME=dev
ENV PROJECT=wendyos

# ... avoid hanging the container creation
# See <https://grigorkh.medium.com/fix-tzdata-hangs-docker-image-build-cdb52cc3360d>
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install the required packages
RUN apt-get update && \
    apt-get -qy upgrade && \
    apt-get -qy install \
        gawk wget git-core diffstat texinfo gcc-multilib \
        build-essential chrpath socat cpio \
        python3 python3-pip python3-pexpect python3-venv python3-git \
        xz-utils bzip2 unzip libxml2-utils debianutils iputils-ping \
        python3-jinja2 python3-yaml libsdl1.2-dev xterm make \
        xsltproc docbook-utils fop dblatex xmlto git-lfs u-boot-tools \
        strace tree fdisk efitools uuid-runtime \
        lz4 zstd liblz4-tool graphviz \
        python3-gi python3-gi-cairo gir1.2-gtk-3.0 x11-apps \
        libncurses5-dev libncursesw5-dev bison flex patchutils \
        libssl-dev ca-certificates locales sudo mc quilt vim pkg-config \
        gdisk dosfstools rsync bmap-tools && \
    apt-get -qy clean

# By default, Ubuntu uses dash as an alias for sh.
# Dash does not support the source command needed for setting up the build
# environment in CMD. Use bash as an alias for sh.
RUN rm /bin/sh && ln -s bash /bin/sh

# Configure en_US.UTF-8 (Yocto build fails without any locale set)
RUN locale-gen --purge en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
COPY ./files/build.locale /etc/default/locale

# The running container writes all the build artifacts to a host directory (outside the container).
# The container can only write files to host directories, if it uses the same user ID and
# group ID owning the host directories. The host_uid and group_uid are passed to the docker build
# command with the --build-arg option. By default, they are both 1001. The docker image creates
# a group with host_gid and a user with host_uid and adds the user to the group. The symbolic
# name of the group and user is cuteradio.
ARG host_uid=1000
ARG host_gid=1000
#RUN groupadd --gid $host_gid $USER_NAME
#RUN useradd \
#    --uid $host_uid \
#    --gid $host_gid \
#    --shell /bin/bash \
#    --create-home \
#    $USER_NAME

RUN set -eux; \
    # rename user and group 1000 -> dev
    usermod -l "${USER_NAME}" -d "/home/${USER_NAME}" -m ubuntu; \
    groupmod -n "${USER_NAME}" ubuntu || true; \
    usermod -s /bin/bash "${USER_NAME}"; \
    mkdir -p "/home/${USER_NAME}" && chown -R "${USER_NAME}:${USER_NAME}" "/home/${USER_NAME}"

# Configure passwordless sudo for the sudo group (using same format as main sudoers)
RUN echo '%sudo ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/nopasswd && \
    chmod 0440 /etc/sudoers.d/nopasswd

# Allow 'dev' user to run sudo
RUN usermod -aG sudo ${USER_NAME}

# Add direct sudoers entry for dev user (in case group-based rule doesn't work)
RUN echo 'dev ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/dev && \
    chmod 0440 /etc/sudoers.d/dev

# Set password for dev user
RUN echo 'dev:wendyos' | chpasswd

COPY files/.bash_history /home/$USER_NAME

# Customize the '.bashrc' file
RUN echo "alias mc='mc -a'" >> /home/${USER_NAME}/.bashrc

# RUN mkdir -p /home/$USER_NAME/.pureline
# COPY ./files/.pureline/ /home/$USER_NAME/.pureline

# Install fzf
RUN git clone --depth 1 https://github.com/junegunn/fzf.git /home/${USER_NAME}/.fzf && \
    /home/${USER_NAME}/.fzf/install --key-bindings --completion --no-update-rc

# Either manually source ~/.fzf.bash or enable the command below:
# RUN echo '[ -f ~/.fzf.bash ] && source ~/.fzf.bash' >> ~/.bashrc

# By default, docker runs as root. However, Yocto builds should not be run as root, but as a
# normal user. Hence, we switch to the newly created user.
USER $USER_NAME
WORKDIR /home/$USER_NAME
